/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Spheron */

#ifndef _Included_Spheron
#define _Included_Spheron
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Spheron
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Spheron_test
  (JNIEnv *, jobject);

/*
 * Class:     Spheron
 * Method:    mconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Spheron_mconnect
  (JNIEnv *, jobject);

/*
 * Class:     Spheron
 * Method:    row
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Spheron_row
  (JNIEnv *, jobject);

/*
 * Class:     Spheron
 * Method:    rolltopos
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_Spheron_rolltopos
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
